name: Node.js CI/CD to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Installing dependencies and building the Frontend
      - name: Install Frontend Dependencies
        run: |
          cd MTM-Frontend
          npm install

      - name: Build Frontend
        run: |
          cd MTM-Frontend
          npm run build

      # Deployment to EC2 (for the backend)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd MotherToMother/MTM-Backend/
            git pull
            npm install
            sudo systemctl restart mtm-server.service
